version: "3.1"

services:
  web:
    image: nginx:latest
    ports:
      - "8085:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app

  php:
    image: php:8.0-fpm
    volumes:
      - ./app:/app
