version: "3.1"

services:
  web:
    image: nginx:latest
    ports:
      - "8085:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app

  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    volumes:
      - ./app:/app
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_USER: "db_user"
      MYSQL_PASSWORD: "secret"
      MYSQL_DATABASE: "HotelDB"
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3307:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9
    depends_on:
      - mysql
    ports:
      - "10003:80"
    environment:
      - PMA_HOST=mysql
volumes:
  mysqldata: {}
